### ISSUE TITLE
After uploading the web files to the host

### ISSUE THREAD

**Issue by Ongz1337** [rogeraabbccdd/Warmod-Plus#3]
After uploading the web files to the host, it shows ERROR HTTP 500

Anyone, please help me.

**Comment by Ongz1337** [comment]
PHP Error log

`[Tue Oct 22 09:48:54.806355 2019] [php7:warn] [pid 30307] [client 223.204.241.113:49443] PHP Warning:  mysqli_connect(): (HY000/1045): Access denied for user ''@'localhost' (using password: NO) in /var/www/html/warmod/config.php on line 18
[Tue Oct 22 09:48:54.806404 2019] [php7:warn] [pid 30307] [client 223.204.241.113:49443] PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/warmod/config.php on line 19
[Tue Oct 22 09:48:54.812034 2019] [php7:warn] [pid 30307] [client 223.204.241.113:49443] PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, boolean given in /var/www/html/warmod/index.php on line 212
[Tue Oct 22 09:48:54.812052 2019] [php7:warn] [pid 30307] [client 223.204.241.113:49443] PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/warmod/index.php on line 213
[Tue Oct 22 09:48:54.812080 2019] [php7:warn] [pid 30307] [client 223.204.241.113:49443] PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, null given in /var/www/html/warmod/index.php on line 214
[Tue Oct 22 09:48:54.812092 2019] [php7:warn] [pid 30307] [client 223.204.241.113:49443] PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, boolean given in /var/www/html/warmod/index.php on line 388
[Tue Oct 22 09:48:54.812096 2019] [php7:warn] [pid 30307] [client 223.204.241.113:49443] PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/warmod/index.php on line 399
[Tue Oct 22 09:48:54.812101 2019] [php7:warn] [pid 30307] [client 223.204.241.113:49443] PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, null given in /var/www/html/warmod/index.php on line 400
[Tue Oct 22 09:48:54.812112 2019] [php7:warn] [pid 30307] [client 223.204.241.113:49443] PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, boolean given in /var/www/html/warmod/index.php on line 608
[Tue Oct 22 09:48:54.812117 2019] [php7:warn] [pid 30307] [client 223.204.241.113:49443] PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/warmod/index.php on line 618
[Tue Oct 22 09:48:54.812121 2019] [php7:warn] [pid 30307] [client 223.204.241.113:49443] PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, null given in /var/www/html/warmod/index.php on line 619
[Tue Oct 22 09:48:54.812127 2019] [php7:warn] [pid 30307] [client 223.204.241.113:49443] PHP Warning:  mysqli_close() expects parameter 1 to be mysqli, boolean given in /var/www/html/warmod/index.php on line 740
[Tue Oct 22 09:48:58.046083 2019] [php7:warn] [pid 30306] [client 223.204.241.113:54676] PHP Warning:  mysqli_connect(): (HY000/1045): Access denied for user ''@'localhost' (using password: NO) in /var/www/html/warmod/config.php on line 18, referer: http://dg-pug.tk/warmod/
[Tue Oct 22 09:48:58.046164 2019] [php7:warn] [pid 30306] [client 223.204.241.113:54676] PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/warmod/config.php on line 19, referer: http://dg-pug.tk/warmod/
[Tue Oct 22 09:48:59.674881 2019] [php7:warn] [pid 30306] [client 223.204.241.113:54676] PHP Warning:  mysqli_connect(): (HY000/1045): Access denied for user ''@'localhost' (using password: NO) in /var/www/html/warmod/config.php on line 18
[Tue Oct 22 09:48:59.674928 2019] [php7:warn] [pid 30306] [client 223.204.241.113:54676] PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/warmod/config.php on line 19
[Tue Oct 22 09:48:59.675354 2019] [php7:warn] [pid 30306] [client 223.204.241.113:54676] PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, boolean given in /var/www/html/warmod/index.php on line 212
[Tue Oct 22 09:48:59.675368 2019] [php7:warn] [pid 30306] [client 223.204.241.113:54676] PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/warmod/index.php on line 213
[Tue Oct 22 09:48:59.675375 2019] [php7:warn] [pid 30306] [client 223.204.241.113:54676] PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, null given in /var/www/html/warmod/index.php on line 214
[Tue Oct 22 09:48:59.675390 2019] [php7:warn] [pid 30306] [client 223.204.241.113:54676] PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, boolean given in /var/www/html/warmod/index.php on line 388
[Tue Oct 22 09:48:59.675396 2019] [php7:warn] [pid 30306] [client 223.204.241.113:54676] PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/warmod/index.php on line 399
[Tue Oct 22 09:48:59.675401 2019] [php7:warn] [pid 30306] [client 223.204.241.113:54676] PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, null given in /var/www/html/warmod/index.php on line 400
[Tue Oct 22 09:48:59.675415 2019] [php7:warn] [pid 30306] [client 223.204.241.113:54676] PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, boolean given in /var/www/html/warmod/index.php on line 608
[Tue Oct 22 09:48:59.675438 2019] [php7:warn] [pid 30306] [client 223.204.241.113:54676] PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/warmod/index.php on line 618
[Tue Oct 22 09:48:59.675443 2019] [php7:warn] [pid 30306] [client 223.204.241.113:54676] PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, null given in /var/www/html/warmod/index.php on line 619
[Tue Oct 22 09:48:59.675450 2019] [php7:warn] [pid 30306] [client 223.204.241.113:54676] PHP Warning:  mysqli_close() expects parameter 1 to be mysqli, boolean given in /var/www/html/warmod/index.php on line 740
[Tue Oct 22 09:49:21.713265 2019] [php7:warn] [pid 30317] [client 223.204.241.113:63019] PHP Warning:  mysqli_connect(): (HY000/1045): Access denied for user ''@'localhost' (using password: NO) in /var/www/html/pug/config.php on line 18
[Tue Oct 22 09:49:21.713354 2019] [php7:warn] [pid 30317] [client 223.204.241.113:63019] PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/config.php on line 19
[Tue Oct 22 09:49:21.718935 2019] [php7:warn] [pid 30317] [client 223.204.241.113:63019] PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 212
[Tue Oct 22 09:49:21.718955 2019] [php7:warn] [pid 30317] [client 223.204.241.113:63019] PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 213
[Tue Oct 22 09:49:21.718962 2019] [php7:warn] [pid 30317] [client 223.204.241.113:63019] PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, null given in /var/www/html/pug/index.php on line 214
[Tue Oct 22 09:49:21.718973 2019] [php7:warn] [pid 30317] [client 223.204.241.113:63019] PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 388
[Tue Oct 22 09:49:21.718978 2019] [php7:warn] [pid 30317] [client 223.204.241.113:63019] PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 399
[Tue Oct 22 09:49:21.718983 2019] [php7:warn] [pid 30317] [client 223.204.241.113:63019] PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, null given in /var/www/html/pug/index.php on line 400
[Tue Oct 22 09:49:21.718995 2019] [php7:warn] [pid 30317] [client 223.204.241.113:63019] PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 608
[Tue Oct 22 09:49:21.719000 2019] [php7:warn] [pid 30317] [client 223.204.241.113:63019] PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 618
[Tue Oct 22 09:49:21.719004 2019] [php7:warn] [pid 30317] [client 223.204.241.113:63019] PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, null given in /var/www/html/pug/index.php on line 619
[Tue Oct 22 09:49:21.719011 2019] [php7:warn] [pid 30317] [client 223.204.241.113:63019] PHP Warning:  mysqli_close() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 740
[Tue Oct 22 09:51:01.780915 2019] [php7:warn] [pid 30309] [client 223.204.241.113:63126] PHP Warning:  mysqli_connect(): (HY000/1045): Access denied for user ''@'localhost' (using password: NO) in /var/www/html/pug/config.php on line 18
[Tue Oct 22 09:51:01.781062 2019] [php7:warn] [pid 30309] [client 223.204.241.113:63126] PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/config.php on line 19
[Tue Oct 22 09:51:01.782053 2019] [php7:warn] [pid 30309] [client 223.204.241.113:63126] PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 212
[Tue Oct 22 09:51:01.782067 2019] [php7:warn] [pid 30309] [client 223.204.241.113:63126] PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 213
[Tue Oct 22 09:51:01.782101 2019] [php7:warn] [pid 30309] [client 223.204.241.113:63126] PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, null given in /var/www/html/pug/index.php on line 214
[Tue Oct 22 09:51:01.782160 2019] [php7:warn] [pid 30309] [client 223.204.241.113:63126] PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 388
[Tue Oct 22 09:51:01.782166 2019] [php7:warn] [pid 30309] [client 223.204.241.113:63126] PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 399
[Tue Oct 22 09:51:01.782171 2019] [php7:warn] [pid 30309] [client 223.204.241.113:63126] PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, null given in /var/www/html/pug/index.php on line 400
[Tue Oct 22 09:51:01.782199 2019] [php7:warn] [pid 30309] [client 223.204.241.113:63126] PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 608
[Tue Oct 22 09:51:01.782220 2019] [php7:warn] [pid 30309] [client 223.204.241.113:63126] PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 618
[Tue Oct 22 09:51:01.782224 2019] [php7:warn] [pid 30309] [client 223.204.241.113:63126] PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, null given in /var/www/html/pug/index.php on line 619
[Tue Oct 22 09:51:01.782259 2019] [php7:warn] [pid 30309] [client 223.204.241.113:63126] PHP Warning:  mysqli_close() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 740
[Tue Oct 22 09:51:35.695876 2019] [php7:warn] [pid 30308] [client 223.204.241.113:63154] PHP Warning:  mysqli_connect(): (HY000/1045): Access denied for user ''@'localhost' (using password: NO) in /var/www/html/pug/config.php on line 18
[Tue Oct 22 09:51:35.695966 2019] [php7:warn] [pid 30308] [client 223.204.241.113:63154] PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/config.php on line 19
[Tue Oct 22 09:51:35.696787 2019] [php7:warn] [pid 30308] [client 223.204.241.113:63154] PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 212
[Tue Oct 22 09:51:35.696802 2019] [php7:warn] [pid 30308] [client 223.204.241.113:63154] PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 213
[Tue Oct 22 09:51:35.696818 2019] [php7:warn] [pid 30308] [client 223.204.241.113:63154] PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, null given in /var/www/html/pug/index.php on line 214
[Tue Oct 22 09:51:35.696887 2019] [php7:warn] [pid 30308] [client 223.204.241.113:63154] PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 388
[Tue Oct 22 09:51:35.696893 2019] [php7:warn] [pid 30308] [client 223.204.241.113:63154] PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 399
[Tue Oct 22 09:51:35.696915 2019] [php7:warn] [pid 30308] [client 223.204.241.113:63154] PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, null given in /var/www/html/pug/index.php on line 400
[Tue Oct 22 09:51:35.696940 2019] [php7:warn] [pid 30308] [client 223.204.241.113:63154] PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 608
[Tue Oct 22 09:51:35.696946 2019] [php7:warn] [pid 30308] [client 223.204.241.113:63154] PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 618
[Tue Oct 22 09:51:35.696951 2019] [php7:warn] [pid 30308] [client 223.204.241.113:63154] PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, null given in /var/www/html/pug/index.php on line 619
[Tue Oct 22 09:51:35.696975 2019] [php7:warn] [pid 30308] [client 223.204.241.113:63154] PHP Warning:  mysqli_close() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 740
[Tue Oct 22 10:12:08.950943 2019] [php7:notice] [pid 30306] [client 78.85.78.219:35391] PHP Notice:  Undefined index: HTTP_USER_AGENT in /var/www/html/includes/SessionManager.php on line 17
[Tue Oct 22 10:15:59.545838 2019] [php7:warn] [pid 30310] [client 223.204.241.113:64019] PHP Warning:  mysqli_connect(): (HY000/1045): Access denied for user ''@'localhost' (using password: NO) in /var/www/html/pug/config.php on line 18
[Tue Oct 22 10:15:59.546049 2019] [php7:warn] [pid 30310] [client 223.204.241.113:64019] PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/config.php on line 19
[Tue Oct 22 10:15:59.547275 2019] [php7:warn] [pid 30310] [client 223.204.241.113:64019] PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 212
[Tue Oct 22 10:15:59.547291 2019] [php7:warn] [pid 30310] [client 223.204.241.113:64019] PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 213
[Tue Oct 22 10:15:59.547307 2019] [php7:warn] [pid 30310] [client 223.204.241.113:64019] PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, null given in /var/www/html/pug/index.php on line 214
[Tue Oct 22 10:15:59.547419 2019] [php7:warn] [pid 30310] [client 223.204.241.113:64019] PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 388
[Tue Oct 22 10:15:59.547426 2019] [php7:warn] [pid 30310] [client 223.204.241.113:64019] PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 399
[Tue Oct 22 10:15:59.547431 2019] [php7:warn] [pid 30310] [client 223.204.241.113:64019] PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, null given in /var/www/html/pug/index.php on line 400
[Tue Oct 22 10:15:59.547470 2019] [php7:warn] [pid 30310] [client 223.204.241.113:64019] PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 608
[Tue Oct 22 10:15:59.547476 2019] [php7:warn] [pid 30310] [client 223.204.241.113:64019] PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 618
[Tue Oct 22 10:15:59.547481 2019] [php7:warn] [pid 30310] [client 223.204.241.113:64019] PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, null given in /var/www/html/pug/index.php on line 619
[Tue Oct 22 10:15:59.547507 2019] [php7:warn] [pid 30310] [client 223.204.241.113:64019] PHP Warning:  mysqli_close() expects parameter 1 to be mysqli, boolean given in /var/www/html/pug/index.php on line 740
[Tue Oct 22 10:17:03.389833 2019] [php7:warn] [pid 30309] [client 223.204.241.113:64074] PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given in /var/www/html/pug/index.php on line 400
[Tue Oct 22 10:17:03.390605 2019] [php7:warn] [pid 30309] [client 223.204.241.113:64074] PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given in /var/www/html/pug/index.php on line 619
[Tue Oct 22 10:17:05.298325 2019] [php7:warn] [pid 30309] [client 223.204.241.113:64074] PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given in /var/www/html/pug/index.php on line 400, referer: http://dg-pug.tk/pug/
[Tue Oct 22 10:17:05.298806 2019] [php7:warn] [pid 30309] [client 223.204.241.113:64074] PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given in /var/www/html/pug/index.php on line 619, referer: http://dg-pug.tk/pug/
[Tue Oct 22 10:17:08.759586 2019] [php7:error] [pid 30309] [client 223.204.241.113:64074] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/pug/steamauth/userInfo.php:6\nStack trace:\n#0 /var/www/html/pug/assets/inc/session.php(4): require_once()\n#1 /var/www/html/pug/index.php(9): require_once('/var/www/html/p...')\n#2 {main}\n  thrown in /var/www/html/pug/steamauth/userInfo.php on line 6
[Tue Oct 22 10:17:13.854692 2019] [php7:error] [pid 30310] [client 223.204.241.113:3788] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/pug/steamauth/userInfo.php:6\nStack trace:\n#0 /var/www/html/pug/assets/inc/session.php(4): require_once()\n#1 /var/www/html/pug/index.php(9): require_once('/var/www/html/p...')\n#2 {main}\n  thrown in /var/www/html/pug/steamauth/userInfo.php on line 6
[Tue Oct 22 10:17:15.716712 2019] [php7:error] [pid 30320] [client 223.204.241.113:59390] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/pug/steamauth/userInfo.php:6\nStack trace:\n#0 /var/www/html/pug/assets/inc/session.php(4): require_once()\n#1 /var/www/html/pug/index.php(9): require_once('/var/www/html/p...')\n#2 {main}\n  thrown in /var/www/html/pug/steamauth/userInfo.php on line 6
[Tue Oct 22 10:17:16.867605 2019] [php7:error] [pid 30324] [client 223.204.241.113:31493] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/pug/steamauth/userInfo.php:6\nStack trace:\n#0 /var/www/html/pug/assets/inc/session.php(4): require_once()\n#1 /var/www/html/pug/index.php(9): require_once('/var/www/html/p...')\n#2 {main}\n  thrown in /var/www/html/pug/steamauth/userInfo.php on line 6
[Tue Oct 22 10:17:17.380562 2019] [php7:error] [pid 30321] [client 223.204.241.113:51260] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/pug/steamauth/userInfo.php:6\nStack trace:\n#0 /var/www/html/pug/assets/inc/session.php(4): require_once()\n#1 /var/www/html/pug/index.php(9): require_once('/var/www/html/p...')\n#2 {main}\n  thrown in /var/www/html/pug/steamauth/userInfo.php on line 6
[Tue Oct 22 10:20:47.514072 2019] [php7:error] [pid 30306] [client 223.204.241.113:64245] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/pug/steamauth/userInfo.php:6\nStack trace:\n#0 /var/www/html/pug/assets/inc/session.php(4): require_once()\n#1 /var/www/html/pug/index.php(9): require_once('/var/www/html/p...')\n#2 {main}\n  thrown in /var/www/html/pug/steamauth/userInfo.php on line 6
[Tue Oct 22 10:20:48.685442 2019] [php7:error] [pid 30307] [client 223.204.241.113:57823] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/pug/steamauth/userInfo.php:6\nStack trace:\n#0 /var/www/html/pug/assets/inc/session.php(4): require_once()\n#1 /var/www/html/pug/index.php(9): require_once('/var/www/html/p...')\n#2 {main}\n  thrown in /var/www/html/pug/steamauth/userInfo.php on line 6
/var/www/get5-web/venv/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py:2513: Warning: '@@tx_isolation' is deprecated and will be removed in a future release. Please use '@@transaction_isolation' instead
  cursor.execute('SELECT @@tx_isolation')
[Tue Oct 22 10:20:53.201056 2019] [mpm_prefork:notice] [pid 30301] AH00169: caught SIGTERM, shutting down
[Tue Oct 22 10:20:53.367362 2019] [mpm_prefork:notice] [pid 31164] AH00163: Apache/2.4.29 (Ubuntu) mod_wsgi/4.5.17 Python/2.7 configured -- resuming normal operations
[Tue Oct 22 10:20:53.367463 2019] [core:notice] [pid 31164] AH00094: Command line: '/usr/sbin/apache2'
[Tue Oct 22 10:20:53.753141 2019] [php7:error] [pid 31170] [client 223.204.241.113:3476] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/pug/steamauth/userInfo.php:6\nStack trace:\n#0 /var/www/html/pug/assets/inc/session.php(4): require_once()\n#1 /var/www/html/pug/index.php(9): require_once('/var/www/html/p...')\n#2 {main}\n  thrown in /var/www/html/pug/steamauth/userInfo.php on line 6
[Tue Oct 22 10:20:54.967453 2019] [php7:error] [pid 31171] [client 223.204.241.113:35731] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/pug/steamauth/userInfo.php:6\nStack trace:\n#0 /var/www/html/pug/assets/inc/session.php(4): require_once()\n#1 /var/www/html/pug/index.php(9): require_once('/var/www/html/p...')\n#2 {main}\n  thrown in /var/www/html/pug/steamauth/userInfo.php on line 6
[Tue Oct 22 10:20:55.333840 2019] [php7:error] [pid 31169] [client 223.204.241.113:14720] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/pug/steamauth/userInfo.php:6\nStack trace:\n#0 /var/www/html/pug/assets/inc/session.php(4): require_once()\n#1 /var/www/html/pug/index.php(9): require_once('/var/www/html/p...')\n#2 {main}\n  thrown in /var/www/html/pug/steamauth/userInfo.php on line 6
[Tue Oct 22 10:21:11.355762 2019] [php7:error] [pid 31172] [client 223.204.241.113:62790] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/pug/steamauth/userInfo.php:6\nStack trace:\n#0 /var/www/html/pug/assets/inc/session.php(4): require_once()\n#1 /var/www/html/pug/index.php(9): require_once('/var/www/html/p...')\n#2 {main}\n  thrown in /var/www/html/pug/steamauth/userInfo.php on line 6
[Tue Oct 22 10:21:34.256992 2019] [mpm_prefork:notice] [pid 31164] AH00169: caught SIGTERM, shutting down
[Tue Oct 22 10:21:34.424718 2019] [mpm_prefork:notice] [pid 31213] AH00163: Apache/2.4.29 (Ubuntu) mod_wsgi/4.5.17 Python/2.7 configured -- resuming normal operations
[Tue Oct 22 10:21:34.424826 2019] [core:notice] [pid 31213] AH00094: Command line: '/usr/sbin/apache2'
`

**Comment by Ongz1337** [comment]
Fixed by 

sudo apt-get install php-curl
sudo service apache2 restart
