### ISSUE TITLE
blank page (index.php) after login via Steam!

### ISSUE THREAD

**Issue by MikkelDK** [rogeraabbccdd/Warmod-Plus#6]
Hi,

Blank/White page, after login of Steam!
**OS: Ubuntu 19.10
Apache2 - PHP 7.3**

```
PHP Warning:  date_default_timezone_get() expects exactly 0 parameters, 1 given in /var/www/html/warmod/libs/sql.php on line 10
PHP Warning:  date_default_timezone_get() expects exactly 0 parameters, 1 given in /var/www/html/warmod/libs/sql.php on line 10
PHP Notice:  Undefined offset: 0 in /var/www/html/warmod/libs/pages/sidebar.php on line 39
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Player::__construct() must be of the type array, null given, called in /var/www/html/warmod/libs/pages/sidebar.php on line 39 and defined in /var/www/html/warmod/libs/class/player.php:232\nStack trace:\n#0 /var/www/html/warmod/libs/pages/sidebar.php(39): Player->__construct(NULL)\n#1 /var/www/html/warmod/index.php(51): require_once('/var/www/html/w...')\n#2 {main}\n  thrown in /var/www/html/warmod/libs/class/player.php on line 232
PHP Warning:  date_default_timezone_get() expects exactly 0 parameters, 1 given in /var/www/html/warmod/libs/sql.php on line 10
PHP Notice:  Undefined offset: 0 in /var/www/html/warmod/libs/pages/sidebar.php on line 39
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Player::__construct() must be of the type array, null given, called in /var/www/html/warmod/libs/pages/sidebar.php on line 39 and defined in /var/www/html/warmod/libs/class/player.php:232\nStack trace:\n#0 /var/www/html/warmod/libs/pages/sidebar.php(39): Player->__construct(NULL)\n#1 /var/www/html/warmod/index.php(51): require_once('/var/www/html/w...')\n#2 {main}\n  thrown in /var/www/html/warmod/libs/class/player.php on line 232
```

Any fix, to get fixed? :D

**Comment by MikkelDK** [comment]
The problem still exists with settings.php ^^
